# Generated by Django 3.2.16 on 2022-10-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.JSONField(default={}),
        ),
    ]
