# Generated by Django 4.1.2 on 2022-10-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedule',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
