# Generated by Django 4.1.2 on 2022-10-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.JSONField(),
        ),
    ]
