# Generated by Django 4.1.2 on 2022-11-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleShiftSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleId', models.IntegerField()),
                ('data', models.JSONField()),
            ],
        ),
    ]
