# Generated by Django 4.1.2 on 2022-11-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_singleshiftschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleshiftschedule',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
